return {
  formatters_by_ft = {
    lua = { "stylua" },
    css = { "prettier" },
    scss = { "prettier" },
    html = { "prettier" },
    javascript = { "prettier" },
    typescript = { "prettier" },
    javascriptreact = { "prettier" },
    typescriptreact = { "prettier" },
    json = { "prettier" },
    jsonc = { "prettier" },
    markdown = { "prettier" },
    yaml = { "prettier" },
    svelte = { "prettier" },
    vue = { "prettier" },
    graphql = { "prettier" },
    prisma = { "prettier" },
    php = { "php-cs-fixer", "prettier" },
    go = { "gofmt", "goimports" },
  },
  format_on_save = {
    timeout_ms = 500,
    lsp_fallback = true,
  },
}
