-- Default configs (may be replaced on upstream JaKooLit update)
require("configs.settings")
require("configs.keybinds")

-- User configs (safe to edit)
require("user-configs.startup_apps")
require("user-configs.envariables")
require("user-configs.monitors")
require("user-configs.window_rules")
require("user-configs.user_decor_animations")
require("user-configs.user_keybinds")
require("user-configs.user_settings")
